experiment: prelim
seed: 42
trials: 2

output:
  dir: outputs
  tag: astar-manhattan

maze:
  generator: dfs_backtracker
  sizes:
    - [21, 21]
    - [31, 31]
    - [41, 41]

search:
  algorithm: a_star
  heuristic: manhattan
  connectivity: 4
